### ISSUE TITLE
comments - can we have something for mere mortals?

### ISSUE THREAD

**Issue by kapitainsky** [netinvent/npbackup#26]
Now when I can finally try it on macOS I allow myself to have few comments:

1. It is very cool and well designed solution - kudos to you
2. It seems a bit geeky (at least for me)  on the surface - I really struggle how to make it work e.g. with restic rclone back end. What I mean is hat maybe I can make it to work but I see very steep learning curve for average user to start using it. Maybe it is just documentation and few straight in your eyes examples missing which would be mega handy.
3.  I have read your laptop backup approach - nice - but for example me I would love to be able not to run backup only when it is too old. I know how to make my laptop to wake up at given time. I want to use snapshots specific to my OS - some pre/post backup hooks to run custom scripts would be great - then I can handle it.
4. What about having multiple repos? I do backup to few. I would love to have an option to switch between them.

These are just comments - or wish list - I do not expect that all can happen. But I can still wish:)

**Comment by deajan** [comment]
Thanks for your feedback

1. Thanks ;)
2. Yes, it was first designed for myself, and there's alot of place for documentation improvements
3. Well you can still schedule your backups using `--force` option which will avoid the time checks. Pre and post backup script hooks already exist, including timeouts, as seen in the screenshot 
![image](https://github.com/netinvent/npbackup/assets/4681318/83a18b9f-9cc5-41cd-b55c-216a8301c3f6)
4. I'd say one config file per repo... You can load various config files with `--config-file`.

**Comment by kapitainsky** [comment]
Thank you for quick response. 

I am still early with using it:) Genuinely think that it is something I will use.

And then I will be PITA with all requests and comments:)

Thank you again.

**Comment by deajan** [comment]
Closing since no issue ;)
Feel free to open other issues if needed.

**Comment by deajan** [comment]
@kapitainsky I'm currently developping v2.3 which has an operation panel to deal with multiple repositories (for check/forget/prune operations).

> What about having multiple repos? I do backup to few. I would love to have an option to switch between them.

Could you explain what you had in mind ?

**Comment by deajan** [comment]
Also, I'm developping a multi repository version, in order to have that privileged client that can check/forget/prune.

I'll happily take requests. Of course the gui is ugly for now as in dev :)

![image](https://github.com/netinvent/npbackup/assets/4681318/9857fa53-7747-4d03-9e4c-a0e0a3a42c8f)

**Comment by deajan** [comment]
v3-beta1 fully implements multiple repository support, group settings support as well as the above housekeeping functions.
