### ISSUE TITLE
Can't change hostname

### ISSUE THREAD

**Issue by andrewchen5678** [netinvent/npbackup#32]
I tried to make Machine identifier to b a hard coded value different than hostname but it is still backed up with the machine's hostname on windows.

I was backing up through restic's rest-server, not sure if it makes any difference.

**Comment by deajan** [comment]
Not sure what we're talking about. The machine identifier `identity: machine_id` is only used for prometheus metrics so far.
It's restic itself that uses the %COMPUTERNAME% variable on Windows.

If you want the hostname to be changed in the restic backups, you'll need to pass `--hostname "yourhost"` to `backup: additional_parameters`.

**Comment by andrewchen5678** [comment]
got it, I was confused about it. Thanks.
