### ISSUE TITLE
QUESTION - npbackup log file location

### ISSUE THREAD

**Issue by GuitarBilly** [netinvent/npbackup#48]
hello and first, thank you for the creation of npbackup!

**I have questions on the npbackup logfile and the location of it.**

On my workstation i have put npbackup in /usr/local/bin/ as suggested. Then I created an application "icon" (.desktop file) that starts npbackup via bash as follows:
`/usr/local/bin/npbackup --config-file=/home/linux/npbackup/npbackup.conf`

This is for a non priviliged user backing up some paths in the home folder. With this i get repeated messages about the logfile:
```
Cannot create logfile. Trying to obtain temporary log file.
Message: [Errno 13] Permission denied: '/usr/local/bin/npbackup.log'
Trying temporary log file in /tmp/ofunctions.logger_utils.log
[Errno 13] Permission denied: '/usr/local/bin/npbackup.log'
Using [/tmp/ofunctions.logger_utils.log]
2024-01-13 16:18:38,172 :: WARNING :: Failed to use log file "/usr/local/bin/npbackup.log", [Errno 13] Permission denied: '/usr/local/bin/npbackup.log'
Using [/tmp/ofunctions.logger_utils.log].
2024-01-13 16:18:38,173 :: INFO :: npbackup v2.2.1-P7-x64 2023082801 - GUI enabled - Copyright (C) 2022-2023 NetInvent
...
```

Now when i run 
`npbackup --config-file=/home/linux/npbackup/npbackup.conf`
instead then the logfile is created in whatever path i launch this command, i.e. /home/linux/npbackup/. I would prefer to keep the logfile for future reference so /tmp/ofunctions.logger_utils.log is not really working.
My workaround is to do a cd /path/for/my/npbackup/logfile/ before calling npbackup without leading path.

My questions:
1) the logfile location is not fixed or configurable, correct?
2) is there a reason or rationale for this behavior?

**Comment by deajan** [comment]
As of current NPBackup version, logfile path is not configurable.
New version of NPBackup is comming soon, and the workflow will look like:

- If --logfile=<path> then create logfile in <path>
- else if `/var/log` exists and is writable, then create logfile there
- else if current directory is writable, then create logfile there
- else create logfile in tmpdir

Is that behavior something you'd expect ?

**Comment by GuitarBilly** [comment]
yes this behaviour makes sense to me.

Can you elaborate on how to handle the situation if the --logfile= location cannot be written to? I would expect to throw an error and abort as the user explicitly/deliberately wants to override the logfile location.

But (as you already described) without --logfile= provided I would expect it to try `/var/log` then `currentdir` then `tmpdir`.

**Comment by deajan** [comment]
IMO, even with --logfile=<unwritable path>, I prefer the backups to run.
Imagine being stuck because your log partition is full, and no backup is run anymore.

**Comment by GuitarBilly** [comment]
Fair enough, and I think either way will be an improvement! 

Do you want to keep this issue open for tracking of the feature?
Else it can be closed as my question is answered.

**Comment by deajan** [comment]
Thanks for the "housekeeping", but yes, I'll keep that open until everything is implemented.
I've rewritten the logging code after the CLI/GUI split, and it's not writing to `/var/log` by default right now.
