### ISSUE TITLE
Version 3 alpha3 not parsing date in negative timezone

### ISSUE THREAD

**Issue by markft** [netinvent/npbackup#53]
The npbackup/npbackup/gui/__main__.py  line 547

  r"[0-9]{4}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9]\..***\+**[0-2][0-9]:[0-9]{2}",

This + needs to be + or -
I'm in EST which is -04:00

**Comment by deajan** [comment]
Good catch, fixed in https://github.com/netinvent/npbackup/commit/dd4c6bec7183a85628e4f0eac6a0d74f84e31d06

Thanks.
