### ISSUE TITLE
3.0beta2 failed to initialize repo

### ISSUE THREAD

**Issue by smpltechno** [netinvent/npbackup#58]
Running 3.0.0-beta2 commit f219d4e:
![image](https://github.com/netinvent/npbackup/assets/57241767/348760ee-3d6b-4f2d-a421-b995eff239d2)

It cannot init a fresh repo.

**Comment by deajan** [comment]
Thanks for your feedback.

Make an initial backup to initialize the repo.
I'll improve the message so this becomes more clear.

**Comment by deajan** [comment]
I've suppressed the message for the first run, and also improved logs.
I'll compile beta3 in the next days.
