### ISSUE TITLE
repo stats window does not scroll

### ISSUE THREAD

**Issue by GuitarBilly** [netinvent/npbackup#63]
v3.0.0.1.rc1
https://github.com/netinvent/npbackup/releases/tag/v3.0.0-rc1

When running stats on a repo the tiny window does not scroll so it appears nothing happens after you start stats.
This is a minor issue for me since functionality works and it appears as cosmetic.

steps to reproduce:
1. start npbackup-gui with one repo config
2. select Operations
3. select Repo Statistics
4.  choose a Repo (group) and press any of the Apply

screenshot immediately after starting stats:
![afbeelding](https://github.com/netinvent/npbackup/assets/38086529/582e5c5b-fca5-4468-acc3-9a20f99fe14f)

screenshot after stats finished:
![afbeelding](https://github.com/netinvent/npbackup/assets/38086529/0f18277a-b1d1-451f-8bd1-77bc9906ae42)

If the many execution step and status/debug messages would be skipped then the one important line could be printed visible for the user, i.e.:

> Running stats for repo default
> {"total_size":42426270,"total_file_count":749,"snapshots_count":10}

instead of

> 
> 
> Running stats for repo default
> 
> Getting stats of repo default
> {"total_size":42426270,"total_file_count":749,"snapshots_count":10}
> 
> Repo statistics command success
> 
> Runner took 1.648825 seconds for stats
> 
> Finished execution group operations
> 
> Runner took 1.649909 seconds for group_runner
> 

Or one can question the size of the Last Messages  window vs Debug Message window. Do we really expect so many errors to be displayed to the user?     :-)
Anyway there are 1000 solutions so I leave it to you to ponder upon.

**Comment by deajan** [comment]
So actually I disabled the autoscroll because it slowed down when there were alot of messages.
Also, I don't filter restic output here, so I won't be able to "skim" the text down.
Of course, the suggestion to make the debug message field smaller than the actual output makes sense ^^
I'll update this for RC2.

**Comment by deajan** [comment]
Current git master now scrolls unless we have list or backup operations, which produce way too much output and make autoscrolling slow.
Also resized stdout log and tried to filter out empty lines.

You can try by installing the git master, or wait for a RC2 release which hopefully should happen somewhere in July.
Feel free to re-open the issue if needed.
