### ISSUE TITLE
manager password bug at first configuration

### ISSUE THREAD

**Issue by GuitarBilly** [netinvent/npbackup#65]
v3.0.0.1.rc1
https://github.com/netinvent/npbackup/releases/tag/v3.0.0-rc1

if you first set up a configuration the manager password is not remembered.

steps to reproduce:
1. start `npbackup-gui`
2. `Load configuration`
3. set name to npbackup.v3.trial.conf and press `New config`
4. tab `Destination`
5. fill in `repo URI` and `repo password`
6. `Set permissions`, enter `Manager Password` and press `Accept`
7. `Accept` to save configuration, press `OK`
8. press `Configure`, goto tab `Destination`
9. rmb on URI <Encrypted_Data> and select Show decrypted
10. watch error "No manager password defined, cannot show unencrypted"
![afbeelding](https://github.com/netinvent/npbackup/assets/38086529/00ac1944-6033-4280-b147-eddaa978f852)

It seems the first time the config is created and accepted the Manager Password is not saved.
When you enter it  once again via the `Set permissions` then it is working.

.

**Comment by deajan** [comment]
I was pretty sure I did get rid of that bug.
I'll have a look.

**Comment by deajan** [comment]
Solved in current git master.

You can try by installing the git master, or wait for a RC2 release which hopefully should happen somewhere in July.
Feel free to re-open the issue if needed.
