### ISSUE TITLE
retention policy inheritance

### ISSUE THREAD

**Issue by GuitarBilly** [netinvent/npbackup#66]
v3.0.0.1.rc1
https://github.com/netinvent/npbackup/releases/tag/v3.0.0-rc1

How can one restore the retention policy Group enheritance once it is removed?

steps to remove the enheritance:
1. start npbackup-gui
2. open configuration
3. tab Retention policy
4. fill in  six new values for each `Repo: default` policy 
5. fill in  six new values for each `Group: default_group` policy
6. select `Repo: default` and the [G] have disappeared
7. no way to get the [G] group enheritance back? i tried clearing boxes, set new values for Group etc.

screenshots
step4:
![afbeelding](https://github.com/netinvent/npbackup/assets/38086529/786442fd-76d5-43d6-be86-26baa35adb9a)

step5:
![afbeelding](https://github.com/netinvent/npbackup/assets/38086529/901727ee-739d-4f60-a49f-208a519079ac)

step6:
![afbeelding](https://github.com/netinvent/npbackup/assets/38086529/a8119946-9a22-48a2-b870-e2aa1cb10341)

step7:
![afbeelding](https://github.com/netinvent/npbackup/assets/38086529/7dd67a5e-9329-41d7-ae0d-056c3acbed08)
![afbeelding](https://github.com/netinvent/npbackup/assets/38086529/71954c9e-dd06-43be-8d39-826c9cad01a5)
![afbeelding](https://github.com/netinvent/npbackup/assets/38086529/516bd429-a52a-415f-88c1-8aef595115ce)
![afbeelding](https://github.com/netinvent/npbackup/assets/38086529/a45cef64-2b8d-49df-a015-bd0375832fa7)
![afbeelding](https://github.com/netinvent/npbackup/assets/38086529/c21ca2bf-ca03-496d-be45-3ef5f1ec1275)

.

**Comment by deajan** [comment]
Thank you for your feedback with all those issues :)
I am currently with **very** limited internet access.
I'll try to reproduce the bug and report back next month, unless internet gets good ^^

**Comment by deajan** [comment]
So the bug was fairly simple. The GUI gave "" as empty string, which in inheritance comparaison wasn't None.
You can try current master or wait until RC2 release somewhere in July.
Feel free to re-open the issue if needed.

**Comment by deajan** [comment]
Solving the manager password issue introduced another inheritance issue.
I'll keep this open as placeholder for the current inheritance bug, which can be triggered the same way.

**Comment by deajan** [comment]
Finally pushed the fixes for the inheritance issues.
RC2 is coming shortly.
