### ISSUE TITLE
Windows Environment Variables

### ISSUE THREAD

**Issue by BJSchmidt** [netinvent/npbackup#67]
v3.0.0.1.rc1
https://github.com/netinvent/npbackup/releases/tag/v3.0.0-rc1
Windows 11

Hello,

I am very excited about the pending v3 release. 

I am testing on Windows 11.

Environment variables do not seem to work when created in the gui. I have tried both Encrypted and Unencrypted variables. I'm specifically testing AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and am using Wasabi s3 for my destination. The settings are written to the config file, but don't seem to have an effect when trying to connect to the repo (not being passed to restic / restic's session's env?).

I am able to set the environment variables manually in powershell with  `$Env:AWS_ACCESS_KEY_ID='<key>'` and  `$Env:AWS_SECRET_ACCESS_KEY='<key>'` and then run `npbackup-gui.exe` from that session, and it works fine.

**Comment by deajan** [comment]
I was pretty sure this worked since I used it with S3 repos in my test scenarios.
The GUI and the CLI use the same engine, so what works in CLI should work in GUI.
Can you confirm that CLI also doesn't work ?

**Comment by deajan** [comment]
Well it looks like I did rename the variables at some time, and forget to update the corresponding code.
Should work now in master.

You can try by installing the git master, or wait for a RC2 release which hopefully should happen somewhere in July.
