### ISSUE TITLE
ERROR :: Cannot decode JSON from restic data: the JSON object must be str, bytes or bytearray, not bool

### ISSUE THREAD

**Issue by chrispersonal** [netinvent/npbackup#98]
Windows v3.0.0-rc6-pub-3.1.1-x64

Consistently seeing this error when the following is run via TaskScheduler  or cmdline with admin privileges:
`-c "npbackup.conf" --group-operation backup --repo-group default_group --run-as-cli`

However, if `npbackup-gui.exe -c npbackup.conf --backup --run-as-cli` is run from the cmdline, this error does not appear.

Also seeing `ERROR :: Cannot find processed bytes: 'total_bytes_processed'` with same symptoms. Let me know if you want a separate issue for that message.

**Comment by deajan** [comment]
I've rewritten RC6 to include a way faster JSON decoder. It looks like it doesn't decode everything the way it's supposed to.
I'll have a look.

**Comment by deajan** [comment]
New RC released including the fix.
